System:
  window_width: 1000
  window_height: 800
  video_width: 600
  video_height: 400
  state_width: 96
  state_height: 96
  fps: 60
  zoom_follow: True

Arena:
  ground_friction: 1e-1

Colors:
  red: !!python/tuple [255, 0, 0]
  green: !!python/tuple [0, 255, 0]
  oxford_blue: !!python/tuple [0, 19, 61]
  white: !!python/tuple [255, 255, 255]
  black: !!python/tuple [0, 0, 0]
  grey: !!python/tuple [40, 40, 40]
  opal: !!python/tuple [198, 216, 211]
  tart_orange: !!python/tuple [240, 84, 79]
  sac_green: !!python/tuple [14, 64, 45]
  emerald: !!python/tuple [91, 186, 111]

Scout:
  body_color: !!python/tuple [56, 4, 14]
  wheel_color: !!python/tuple [30, 30, 30]
  size: 0.02
  body_width: 100
  raycast_color: !!python/tuple [0, 0, 255]
  body_height: 100
  sensor_array_color: !!python/tuple [0, 255, 0]
  body_density: !!python/float 1.0
  wheel_density: !!python/float 1e0
  sensor_array_density: !!python/float 1e-3
  ray_density: !!python/float 1e-8
  turn_speed: !!python/float 1
  acceleration_speed: !!python/float 1e2
  camera_turn_speed: !!python/float 5
